import type { BaseMessage } from '@langchain/core/messages';
import type { AceAgentWorkflowContext } from '../ace_graph_v1/types';

// ── Goal → Step → Task hierarchy ──────────────────────────────────────────

/** Top-level objective. Orchestrator creates one or more goals. */
export interface AceAgentGoal {
    id: string;
    /** What to achieve. */
    objective: string;
    /** Why this goal was chosen. */
    rationale: string;
    /** Dynamic phases to accomplish this goal. */
    steps: AceAgentStep[];
    status: 'pending' | 'in_progress' | 'completed' | 'failed';
}

/** A dynamic phase within a goal — represents a step the agent took toward the goal. */
export interface AceAgentStep {
    id: string;
    /** What this step accomplishes (e.g. "Gather context", "Implement JWT"). */
    phase: string;
    /** Micro-tasks for this step (populated by executor). */
    tasks: AceAgentTask[];
    status: 'in_progress' | 'completed' | 'failed';
    /** Summary output generated by the review node after step evaluation. */
    output?: string;
}

/** A single micro-task — generated one at a time by executor. */
export interface AceAgentTask {
    id: string;
    summary: string;
    type: 'tool' | 'context' | 'searching' | 'speaking';
    payload: Record<string, unknown>;
    status: 'in_progress' | 'completed' | 'failed';
    /** Result from the action node. */
    output?: Record<string, unknown>;
    /** Retry counter — managed by review_task. */
    retry_count: number;
    max_retries: number;
}

// ── State ──────────────────────────────────────────────────────────────────

export interface AceAgentV2State {
    messages: BaseMessage[];
    original_prompt: string;
    context?: AceAgentWorkflowContext;

    /** All goals generated by the orchestrator. */
    goals: AceAgentGoal[];
    /** Currently active goal. */
    current_goal?: AceAgentGoal;
    /** Currently active step within the current goal. */
    current_step?: AceAgentStep;
    /** Currently active micro-task within the current step. */
    current_task?: AceAgentTask;

    /** Breakdown of user prompt into actionable thoughts (set by thought node). */
    thoughts: string[];

    /** Which node produced this state (for tracing). */
    from_node?: string;

    /** Set by stopThreadPrompt — nodes check this to exit gracefully. */
    is_stopped?: boolean;

    /** Internal routing — set by executor/reviewer for conditional edges. */
    target_node?: string;
    /** Reason for target_node redirect — used by orchestrator on re-entry. */
    target_node_reason?: string;

    /** Latest node result — used by reviewer. */
    result_summary: string;
}
