import type { BaseMessage } from '@langchain/core/messages';
import type { AceAgentWorkflowContext } from '../ace_graph_v1/types';

// ── Thought ────────────────────────────────────────────────────────────────

/** A single thought cycle — agent's internal monologue + classified action. */
export interface AceAgentThought {
    /** Internal monologue: what the agent thinks about the current state. */
    thought: string;
    /** Classified next action. */
    action: 'create_step' | 'create_task' | 'done';
    /** Why this action was chosen. */
    reasoning: string;
}

// ── Step → Task hierarchy ──────────────────────────────────────────────────

/** A dynamic phase — represents a step the agent takes toward the user's request. */
export interface AceAgentStep {
    id: string;
    /** What this step accomplishes (e.g. "Gather context", "Implement JWT"). */
    phase: string;
    /** Micro-tasks for this step (populated by executor). */
    tasks: AceAgentTask[];
    status: 'in_progress' | 'completed' | 'failed';
    /** Summary output generated by the review node after step evaluation. */
    output?: string;
}

/** A single micro-task — generated one at a time by executor. */
export interface AceAgentTask {
    id: string;
    summary: string;
    type: 'tool' | 'context' | 'searching' | 'speaking';
    payload: Record<string, unknown>;
    status: 'in_progress' | 'completed' | 'failed';
    /** Result from the action node. */
    output?: Record<string, unknown>;
    /** Retry counter — managed by review_task. */
    retry_count: number;
    max_retries: number;
}

// ── State ──────────────────────────────────────────────────────────────────

export interface AceAgentV2State {
    messages: BaseMessage[];
    original_prompt: string;
    context?: AceAgentWorkflowContext;

    /** History of all completed/failed steps. */
    steps: AceAgentStep[];
    /** History of all tasks across all steps. */
    tasks: AceAgentTask[];
    /** Currently active step. */
    current_step?: AceAgentStep;
    /** Currently active micro-task within the current step. */
    current_task?: AceAgentTask;

    /** History of agent thought cycles (think + classified action). */
    thoughts: AceAgentThought[];

    /** Global iteration counter — incremented each time thought runs. Prevents infinite thought→step loops. */
    global_iteration: number;

    /** Which node produced this state (for tracing). */
    from_node?: string;

    /** Set by stopThreadPrompt — nodes check this to exit gracefully. */
    is_stopped?: boolean;

    /** Internal routing — set by executor/reviewer for conditional edges. */
    target_node?: string;
    /** Reason for target_node redirect — used by orchestrator on re-entry. */
    target_node_reason?: string;

    /** Latest node result — used by reviewer. */
    result_summary: string;
}
