import type { BaseMessage } from '@langchain/core/messages';

// ── Memory ─────────────────────────────────────────────────────────────────

export interface MemoryItem {
    id: string;
    /** Semantic key, e.g. "user_name", "project_stack" */
    key: string;
    /** Category of memory */
    type: 'insight' | 'fact' | 'preference';
    /**
     * Injected into the thought prompt when is_expanded.
     * Acts as a summary/description — the actual full data lives in the store.
     */
    content: string;
    /**
     * Dynamic toggle — set by the agent via action_memory.
     * When true, this memory's content is injected into the thought prompt.
     */
    is_expanded: boolean;
}

// ── Thought Cycle ──────────────────────────────────────────────────────────

/**
 * A single thought → action cycle.
 *
 * Flow:
 *   START → thought → action_dispatcher → [action_* ...] → thought (loop) or END
 *
 * thought produces structured output and builds an actions[] array.
 * dispatcher iterates through actions sequentially, then routes back to thought.
 */
export interface ThoughtCycle {
    /** What is being considered (user prompt, previous action result, etc.). */
    subject: string;
    /** Internal monologue: observation + assessment from thought node. */
    thought: string;
    /** Batched actions — run sequentially within this cycle. */
    actions: ThoughtAction[];
    /**
     * LLM-generated summary of all action results in this cycle.
     * Filled by the dispatcher after all actions complete.
     */
    result_summary?: string;
}

// ── Action (within a cycle) ────────────────────────────────────────────────

export interface ThoughtAction {
    /** What the agent intends to do with this specific action. */
    thought: string;

    /** Target node and reason. */
    target: { name: string; reason: string };

    /** Execution status — dispatcher manages this. */
    status: 'pending' | 'running' | 'done' | 'failed';

    /**
     * File pointer to the action's output data.
     * Stored at /storage/threads/<uid>/cycle/<cycleIdx>/actions/<idx>/output.json
     */
    output?: string;

    /**
     * File pointer to the action's result data.
     * Stored at /storage/threads/<uid>/cycle/<cycleIdx>/actions/<idx>/result.json
     */
    result?: string;
}

// ── Context ─────────────────────────────────────────────────────────────────

export type ContextItemType = 'file' | 'directory' | 'tool';

export interface ContextItemFile {
    id: string;
    type: 'file';
    /** File path as the key */
    key: string;
    summary: string;
    is_expanded: boolean;
    /** Inline stored content — injected into prompt when expanded */
    content: string;
}

export interface ContextItemDirectory {
    id: string;
    type: 'directory';
    /** Directory path as the key */
    key: string;
    summary: string;
    is_expanded: boolean;
    /** Inline stored content — injected into prompt when expanded */
    content: string;
}

export interface ContextItemTool {
    id: string;
    type: 'tool';
    /** tool_call_id as the key */
    key: string;
    summary: string;
    is_expanded: boolean;
    /** File pointer to payload/setup data */
    payload?: string;
    /** File pointer to output/result data */
    output?: string;
}

export type ContextItem = ContextItemFile | ContextItemDirectory | ContextItemTool;

// ── Step (Plan) ───────────────────────────────────────────────────────────

export interface ActionStepItem {
    id: string;
    /** Human-readable goal for this step. */
    goal: string;
    /** Current status. */
    status: 'pending' | 'active' | 'done';
}

// ── State ──────────────────────────────────────────────────────────────────

export interface AceAgentV3State {
    messages: BaseMessage[];
    original_prompt: string;

    /**
     * Global memory hub — all memory items pulled from store at session start.
     */
    memories: MemoryItem[];

    /**
     * Context hub — file, directory, and tool contexts created by action nodes.
     * Each context has payload/output file pointers for large data.
     */
    contexts: ContextItem[];

    /**
     * Step plan — multi-cycle milestones generated by action_step.
     * Each step is a goal that may span multiple thought cycles.
     */
    steps: ActionStepItem[];

    /** Full history of think → act → review cycles. */
    cycles: ThoughtCycle[];

    /** Currently active cycle. */
    current_cycle?: ThoughtCycle;

    /** Global cycle counter for gatekeeping. */
    global_cycle: number;

    /** Which node produced this state (for tracing). */
    from_node?: string;

    /** Internal routing — set by thought/action for conditional edges. */
    target_node?: string;

    /** Reason for target_node redirect. */
    target_node_reason?: string;
}
