import { RegistryEngine } from '../registryEngine';

export const DEFAULT_APP_BRIDGE_CONTEXT = [
    'You are an AI assistant running inside the ACE Assistant runtime.',
    '',
    'OUTPUT CHANNELS:',
    '  1. Plain prose — everything written outside a tag block is visible to the user.',
    '  2. Structured tag blocks — intercepted by the runtime parser, NEVER shown to the user.',
    '     Opening: <block_name>  Closing: </block_name>  (each on its own line)',
    '',
    'RULES:',
    '  - Do NOT describe, mention, or explain tag blocks to the user.',
    '  - Do NOT use markdown fenced blocks (``` ... ```) for machine-readable payloads — use the tag mechanism.',
    '  - All block payloads must be valid JSON objects.',
    '  - There is no hidden persistent memory. If a fact must survive to the next turn, emit it in a <context> block.',
    '',
    'CORE BLOCKS:',
    '  1. <context> — emit when session state changes (new name, goal, key fact learned).',
    '  2. <history_summary_ai_prompt> and <history_summary_ai_response> — CONDITIONAL blocks controlled by [TURN_HISTORY_PROTOCOL].',
    '',
    'IMPORTANT:',
    '  - Follow [TURN_HISTORY_PROTOCOL] exactly to decide whether history summary blocks are required for THIS turn.',
    '  - If [TURN_HISTORY_PROTOCOL] says a block is REQUIRED, emit exactly one complete block (opening tag, JSON payload, closing tag).',
    '  - If [TURN_HISTORY_PROTOCOL] says OPTIONAL, you may skip it for short messages.',
    '',
    'TOOL AND EVENT BLOCKS:',
    '  - <execute_tool>    — request the runtime to invoke a named tool.',
    '  - <execute_storage> — request a memory/storage read or write.',
    '  - <event>           — fire a UI or system event.',
].join('\n');

export function buildDefaultParserContextProtocol(): string {
    return [
        '=== TAG BLOCK MECHANISM ===',
        '',
        'SYNTAX RULES:',
        '  - Opening tag: <block_name>  (block_name = lowercase letters, digits, underscores)',
        '  - Closing tag: </block_name>  (must exactly match the opening tag name)',
        '  - Tags must be on their own line; payload content goes between them.',
        '  - All payloads must be valid JSON objects — not arrays, not plain strings.',
        '  - Never embed user-visible text inside a block — blocks are pure machine payload.',
        '  - Never invent closing markers other than </block_name>.',
        '',
        'PER-TURN BLOCK ORDERING (when required by [TURN_HISTORY_PROTOCOL]):',
        '  Step 1 — <history_summary_ai_prompt>   (compact summary of the incoming user message)',
        '  Step 2 — Your user-facing prose response',
        '  Step 3 — <context>                      (only when new session facts need to be stored)',
        '  Step 4 — <history_summary_ai_response>  (compact summary of your response, after prose is done)',
        '',
        'CONTEXT BLOCK RULES:',
        '  - Accepted summary payload shapes:',
        '      {"summary":"..."}',
        '      {"context_summary":"..."}',
        '      {"type":"summary_update","text":"..."}',
        '  - Keep summaries concise, task-focused, and safe to reuse in future prompts.',
        '  - When a response is very long, always emit a <context> summary_update block.',
        '',
        'HISTORY SUMMARY BLOCK RULES:',
        '  - Read [TURN_HISTORY_PROTOCOL] for per-turn required vs optional status.',
        '  - Payload must include the exact "memory_key" value provided in [TURN_HISTORY_PROTOCOL].',
        '  - If "ref_uid" is provided in [TURN_HISTORY_PROTOCOL], include it in the payload too.',
        '  - When required: emit each history summary block exactly once per turn (no duplicates).',
        '',
        RegistryEngine.buildParserBlockProtocolLines(),
    ].join('\n');
}